# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

pod 'Alamofire', '~> 4.5'
pod 'ObjectMapper', '~> 2.2'
pod 'Hue', '~> 2.0'

target 'Example' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    # Pods for Papara
end
